### PR TITLE
Webm (libvpx) changes

### PR DESCRIPTION
**Pull request by ggarra13**
This change adds libvpx support to CI, FFmpeg build as well as tlRender's extension support.
This is a simple PR to link the libvpx library dynamically. But in fact, it should be built statically.

### CODE REVIEW

**Comment by ggarra13** [comment]
This is a simple PR to link the libvpx library dynamically.  But in fact, it should be built statically.

**Comment by darbyjohnston** [comment]
Doesn't this create a dependency on libvpx being installed on the system?

**Comment by ggarra13** [comment]
Yes.  That's why I mentioned linking them dynamically for now.

This is for you to try on a separate branch, on Linux or macOS to see the video going black.

The dependencies on Linux and macOS are a non issue as you have apt-get and brew.
On Windows, it is also not an issue if you use the media-autobuild_suite which installs Msys, compiles everything for you statically and compiles FFmpeg dynamically.  It is *much* better than using WSL2 as you did.
I am currently updating the documentation on mrv2's README.md about that.

**Comment by ggarra13** [comment]
Don't worry about it.  I remembered I have BuildYASM.cmake and BuildVPX.cmake files in mrViewer 1 (those are the two dependencies needed to compile webm/libvps).  
I'll move them over to my own tlRender copy and I'll do a proper PR with them and with an set( TLRENDER_VPX  OFF ) by default so you don't have to compile it if you don't want it.

**Pull request closed without merging**
