### PR TITLE
Added some disables to FFmpeg when compiling for APPLE.

### PR DESCRIPTION
**Pull request by ggarra13**
Some of these are probably worth moving to all platforms, like --disable-sdl2.

### CODE REVIEW

**Comment by darbyjohnston** [comment]
Thanks, would you mind formatting the changes like the surrounding code? E.g., four spaces for indentation.

**Comment by darbyjohnston** [comment]
What issues were these causing? It looks like they are UI libraries and would only apply to the FFmpeg programs like ffplay, but that should already be disabled with ```--disable-programs```?

**Comment by ggarra13** [comment]
> El 7 ene. 2023, a las 21:23, Darby Johnston ***@***.***> escribió:
> 
> 
> What issues were these causing? It looks like they are UI libraries and would only apply to the FFmpeg programs like ffplay, but that should already be disabled with --disable-programs?

When they were found on disk, they were getting linked in into libavdevice.dylib making it fat and hard to distribute it.

—
Gonzalo Garramuno
***@***.***

**Comment by darbyjohnston** [comment]
In that case it seems like they should be disabled on Linux as well. I believe changing the conditional to ```if(UNIX)``` will disable it for all UNIX based systems (including macOS).

**Comment by ggarra13** [comment]
> El 7 ene. 2023, a las 21:38, Darby Johnston ***@***.***> escribió:
> 
> 
> In that case it seems like they should be disabled on Linux as well. I believe changing the conditional to if(UNIX) will disable it for all UNIX based systems (including macOS).

Yes, that’s probably a better change.

—
Gonzalo Garramuno
***@***.***

**Comment by darbyjohnston** [comment]
Thanks!

**Pull request merged**
