### PR TITLE
Fixed threading issue with RtAudio on Windows and Linux.

### PR DESCRIPTION
**Pull request by ggarra13**
I found out that on Windows, another issue caused by RtAudio would happen which would prevent Drag and Drop in FLTK to work after loading 4 clips with audio. 
The issue with both seems to be that the RtAudio pointer is instantiated within the std::thread body and that creates issues with audio apis which are not multithreaded.  I moved the instantiation of RtAudio outside of the thread, and the issue seems to be fixed.

### CODE REVIEW

**Comment by ggarra13** [comment]
Done.

**Comment by darbyjohnston** [comment]
Actually this is a bit more complicated since the ```RtAudio``` constructor can throw an exception, it should be inside a try/catch block so the program doesn't exit if there is an audio error. Then the other code needs to check whether the ```RtAudio``` pointer is null.

Are you sure this is what's causing issues? How does the audio relate to FLTK drag and drop?

**Comment by ggarra13** [comment]
The audio relates to FLTK drag and drop on Windows as the constructor for WasApi calls CoInitialize() and CoCreateInstance(), which seem the routines that deal with non-threaded behavior and that seems to trigger the conflict.  The FLTK drag and drop behavior makes it so that you can load up to 4 clips without any issue, but beyond that, the FLTK events for drag and drop are not sent to the window.   I found it out by chance when I turned off TLRENDER_AUDIO.

https://github.com/ggarra13/mrv2/assets/8065400/c6968501-50e1-472e-ae24-532af2764b29

With my "fix" all works fine.  I can add a check try/catch block and a check for nullptr, but not sure what I would do in those cases.

**Comment by ggarra13** [comment]
I have modified the patch to, I believe, address your concerns.

**Pull request merged**
